/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 24-Mar-2026 23:45:10
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 4
 * Denominator Length  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2025b.app/extern/include/tmwtypes.h 
 */
const int NL_H = 4;
const float NUM_H[4] = {
     0.9949860584423,   -2.984958175327,    2.984958175327,  -0.9949860584423
};
const int DL_H = 4;
const float DEN_H[4] = {
                   1,   2.989946914092,    -2.979944296952,  0.9899972564945
};
