/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 19-Mar-2026 11:46:05
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yesfloat
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"

/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2025b.app/extern/include/tmwtypes.h 
 */
#define MWSPT_NSEC 7
static float NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
static float NUM[MWSPT_NSEC][3] = {
  {
    0.01310812086282,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
    0.01310812086282,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
     0.0130236025687,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
                   1,                 0,                 0 
  }
};
static float DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
static float DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.976931685814,   0.9778173517663 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.996024562322,    0.996052349253 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.973796930803,   0.9739527948626 
  },
  {
                   1,                 0,                 0 
  }
};
