/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 24-Mar-2026 23:44:43
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 4
 * Denominator Length  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2025b.app/extern/include/tmwtypes.h 
 */
const int NL_L = 4;
const float NUM_L[4] = {
  3.756838019751 ,1.127051405925 ,1.127051405925 ,3.756838019751 
};
const int DL_L = 4;
const float DEN_L[4] = {
                   1,    2.93717072845,    -2.876299723479,  0.9390989403253
};
